#!/usr/bin/env bash

# Run eslint check
echo "Running eslint check..."
bun run eslint:check

# Run type checking
echo "Running type checking..."
bun run typecheck

# Run prettier fix
echo "Running prettier fix..."
bun run prettier:fix

# Run tests
# echo "Running tests..."
# bun run test
